// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VoteOnline.Models
{
    public partial class GetVoteCountsResult
    {
        public string VoteItemId { get; set; }
        public string ItemName { get; set; }
        public int? VoteCount { get; set; }
    }
}
