// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Data;

namespace VoteOnline.Models;

public partial class User
{
    public string UserName { get; set; }

    public virtual ICollection<VoteRecord> VoteRecords { get; set; } = new List<VoteRecord>();

}

public class GetVotePage
{
    public List<string> UserNames { get; set; } = new List<string>(); // 多個 UserName
    public List<VoteItemCount> VoteItemCounts { get; set; } = new List<VoteItemCount>(); // 多個投票結果
	public string Message { get; set; } = string.Empty;
}

//public class VoteRequestDto
//{
//	public string UserName { get; set; }
//	public List<VoteItemDto> VoteItems { get; set; }
//}

public class VoteItemDto
{
	public int VoteItemId { get; set; }
	public string ItemName { get; set; }
}



