// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoteOnline.Models;

public partial class VoteRecord
{
    public int VoteId { get; set; }

    public string UserName { get; set; }

    public string VoteItemId { get; set; }

    public virtual VoteItem VoteItem { get; set; }
}