// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace VoteOnline.Models;

public partial class VoteOnlineContext : DbContext
{
    public VoteOnlineContext(DbContextOptions<VoteOnlineContext> options)
        : base(options)
    {
    }

    public virtual DbSet<VoteCountsView> VoteCountsViews { get; set; }

    public virtual DbSet<VoteItem> VoteItems { get; set; }

    public virtual DbSet<VoteRecord> VoteRecords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VoteCountsView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VoteCountsView");

            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.VoteItemId)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<VoteItem>(entity =>
        {
            entity.HasKey(e => e.VoteItemId).HasName("PK__VoteItem__04803B287FC4EE91");

            entity.Property(e => e.VoteItemId).HasMaxLength(50);
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<VoteRecord>(entity =>
        {
            entity.HasKey(e => e.VoteId).HasName("PK__VoteReco__52F015C287364848");

            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.VoteItemId)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.VoteItem).WithMany(p => p.VoteRecords)
                .HasForeignKey(d => d.VoteItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VoteRecor__VoteI__267ABA7A");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}