// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VoteOnline.Models;

public partial class VoteItem
{
    public int VoteItemId { get; set; }

    public string ItemName { get; set; }

    public virtual ICollection<VoteRecord> VoteRecords { get; set; } = new List<VoteRecord>();
}