// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace VoteOnline.Models;

public partial class VoteOnlineContext : DbContext
{
    public VoteOnlineContext(DbContextOptions<VoteOnlineContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<VoteItem> VoteItems { get; set; }

    public virtual DbSet<VoteItemCount> VoteItemCounts { get; set; }

    public virtual DbSet<VoteRecord> VoteRecords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__Users__C9F28457B7A15071");

            entity.Property(e => e.UserName).HasMaxLength(10);
        });

        modelBuilder.Entity<VoteItem>(entity =>
        {
            entity.HasKey(e => e.VoteItemId).HasName("PK__VoteItem__04803B288E96E315");

            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<VoteItemCount>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VoteItemCounts");

            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<VoteRecord>(entity =>
        {
            entity.HasKey(e => e.VoteId).HasName("PK__VoteReco__52F015C2F7F2717B");

            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(10);

            entity.HasOne(d => d.UserNameNavigation).WithMany(p => p.VoteRecords)
                .HasForeignKey(d => d.UserName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VoteRecor__UserN__286302EC");

            entity.HasOne(d => d.VoteItem).WithMany(p => p.VoteRecords)
                .HasForeignKey(d => d.VoteItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VoteRecor__VoteI__29572725");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}