// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using VoteOnline.Models;

namespace VoteOnline.Models
{
    public partial class VoteOnlineContext
    {
        private IVoteOnlineContextProcedures _procedures;

        public virtual IVoteOnlineContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new VoteOnlineContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IVoteOnlineContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetVoteCountsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class VoteOnlineContextProcedures : IVoteOnlineContextProcedures
    {
        private readonly VoteOnlineContext _context;

        public VoteOnlineContextProcedures(VoteOnlineContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetVoteCountsResult>> GetVoteCountsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetVoteCountsResult>("EXEC @returnValue = [dbo].[GetVoteCounts]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
